services:
  config-downloader:
    image: alpine:latest
    container_name: mcpo-config-downloader
    volumes:
      - config-data:/tmp/config
    restart: no
    command: >
      sh -c "
        apk add --no-cache wget &&
        if [ ! -f /tmp/config/config.json ]; then
          wget -O /tmp/config/config.json https://raw.githubusercontent.com/chaoscode/MCPO/main/config.example.json
        fi &&
        # Ensure proper permissions for the web editor
        chmod 666 /tmp/config/config.json
      "
  config-editor:
    image: lscr.io/linuxserver/code-server:latest
    container_name: mcpo-config-editor
    restart: unless-stopped
    ports:
      - ${HOST_IP:-0.0.0.0}:18020:8443
    volumes:
      - config-data:/config/workspace/config
      - editor-data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${EDITOR_PASS:-changeme}
      - SUDO_PASSWORD=${EDITOR_SUDO_PASS:-changeme}
      - DEFAULT_WORKSPACE=/config/workspace/config
    depends_on:
      config-downloader:
        condition: service_completed_successfully
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo
    restart: unless-stopped
    network_mode: host
    volumes:
      - config-data:/app/config
    env_file:
      - .env
    depends_on:
      config-downloader:
        condition: service_completed_successfully
    healthcheck:
      test: curl --silent --fail "http://${HOST_IP:-0.0.0.0}:18021/docs" || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command:
      - mcpo
      - --config
      - /app/config/config.json
      - --host
      - ${HOST_IP:-0.0.0.0}
      - --port
      - "18021"
      - --api-key
      - ${MCPO_API_KEY:-changeme}
volumes:
  config-data: null
  editor-data: null
networks: {}
